from pathlib import Path
from bs4 import BeautifulSoup
P=Path(__file__).parent/"textbook-edition-20-rule"/"module07.html"
def sh(t,h):
 f=BeautifulSoup(h,"html.parser");t.clear()
 for c in list(f.contents):t.append(c)
s=BeautifulSoup(P.read_text(encoding="utf8"),"html.parser")
def rep(p,h):
 m=[x for x in s.find_all(["p","li","figcaption"]) if x.get_text(" ",strip=True).startswith(p)]
 if len(m)!=1:raise RuntimeError((p,len(m)))
 sh(m[0],h)
R={
"The reason to treat":r"A single dispersion relation describes both Rayleigh–Taylor and Kelvin–Helmholtz instability. Its terms represent shear, buoyancy, capillary tension, and magnetic tension. Removing shear gives the Rayleigh–Taylor limit; removing gravity gives Kelvin–Helmholtz. Section 3 checks five limiting cases before applying the general relation.",
"Two things follow":r"The growth rate $\sigma$ has units of inverse time, so instability matters only relative to an observational or dynamical clock. It also depends on wavenumber $k$. An interface is therefore unstable over a range of wavelengths, and the fastest-growing accessible mode often sets the observed pattern.",
"Magnetic tension rises":r"Magnetic tension contributes a $k^2$ term, whereas capillary tension contributes $k^3$. A perturbation bends the field through a depth of order $1/k$, giving an effective surface tension proportional to $1/k$. Magnetic tension therefore scales like the Kelvin–Helmholtz drive and produces an amplitude threshold rather than a wavelength cutoff. Section 9 uses that threshold to bound the field orientation.",
"Limit 4 deserves":r"Limit 4 reproduces the algebraic growth-rate formula used by Ofman and Thompson for their solar observation. This establishes consistency between the two expressions. It does not compare either expression with data; §9 treats the observational constraints separately.",
"Switch off the shear":r"""With shear and magnetic field removed, equation (3.1) becomes
$$\sigma^2=Agk-\frac{T_sk^3}{\rho_t+\rho_b}.\tag{4.1}$$
Buoyancy dominates at small $k$, while capillary tension dominates at large $k$. Their crossing explains why an inverted water column falls from a glass but can remain suspended in a narrow straw.""",
"That is the straw":r"For water, the capillary cutoff is $\lambda_c=1.71$ cm. A sufficiently narrow tube admits no unstable wavelength and can retain the inverted column. The exact lowest mode depends on wall geometry, which the unbounded-interface model omits. The robust conclusion is that surface tension introduces a centimetre-scale cutoff.",
"For water, $\\nu":r"For water, the viscous scale $0.467$ mm is $63.5$ times smaller than the fastest capillary wavelength $29.7$ mm, so viscosity is negligible. In glycerol, the much larger viscosity gives $\lambda_\nu=5.207$ cm, exceeding the capillary value $2.458$ cm. The dominant small-scale regulator then changes from surface tension to viscosity.",
"A simulation of this":r"Without surface tension, viscosity, magnetic tension, or finite interface thickness, the Rayleigh–Taylor growth rate increases as $\sqrt{k}$. Grid refinement then reveals ever faster unresolved modes rather than a converged solution. Astrophysical calculations must therefore supply a physical small-scale cutoff outside the ideal sharp-interface equations.",
"Equation (5.1) needs":r"In a supernova remnant, the relevant acceleration is not stellar gravity but deceleration of the ejecta as they sweep up ambient gas. In the shell frame, the effective acceleration points from dense ejecta toward the lighter shocked medium. This is the Rayleigh–Taylor unstable ordering.",
"Now switch the shear":r"""With $T_s=B=0$, equation (3.1) gives
$$\sigma^2=\frac{k^2\rho_t\rho_b\Delta U^2}{(\rho_t+\rho_b)^2}+Agk.\tag{6.1}$$
For stable density stratification, $A\lt0$. Gravity suppresses long wavelengths because its term scales as $k$, while shear destabilises short wavelengths through $k^2$. The cutoff therefore occurs at the opposite end of the spectrum from the capillary cutoff.""",
"Near the jet stream":r"For $T=220$ K and lapse rate $6.0\ \mathrm{K\,km^{-1}}$, the dry-air buoyancy frequency is $N=0.01295\ \mathrm{s^{-1}}$. The corresponding period, $2\pi/N$, is $8.1$ minutes.",
"A jet of radius":r"Consider a $100$ pc jet moving at Mach 5 through $10^7$ K gas. With $\mu=0.60$ and $\gamma=5/3$, $c_s=480.6\ \mathrm{km\,s^{-1}}$ and $\Delta U=2403\ \mathrm{km\,s^{-1}}$. For density ratio $\rho_j/\rho_a=0.010$, the shear prefactor is $0.09901$. Taking $k=1/R$ corresponds to wavelength $2\pi R$, already longer than a mode that fits across the jet. Equation (6.1) then gives the most favourable long-wavelength growth estimate.",
"Shimony et al.":r"Shimony et al. (2022) studied a planar Rayleigh–Taylor interface at the National Ignition Facility. A plastic layer of density $1.43\ \mathrm{g\,cm^{-3}}$ contacted foam near $0.08\ \mathrm{g\,cm^{-3}}$. Machined perturbations with mean wavelengths 15 and $30\,\mu$m were followed by x-ray radiography.",
"The paper's abstract":r"The experiment also claims to resolve a factor-of-two discrepancy between analytic and simulated mixing coefficients. Its measured coefficient must therefore be precise enough to distinguish values near 0.05 from values near 0.025. The comparison below tests that discrimination directly.",
"One refutation and":r"Upper panel: the measured mixing coefficient and uncertainty are compared with three proposed values. Both ends of the claimed factor-of-two discrepancy lie within $2\sigma$, so the experiment does not distinguish them. Lower panel: the observed coronal-vortex speed spans $6$–$14\ \mathrm{km\,s^{-1}}$. Both density-weighted and equal-density phase-speed predictions fall inside this band. A factor-2.3 observational range cannot separate predictions differing by a factor 1.62.",
"What such an observation":r"The coronal observation can constrain combinations of density, field orientation, shear, and interface thickness. The following checks distinguish reproduced arithmetic from quantities that the images measure independently.",
"Before any check":r"Three conversions fix the observational precision. At 1 au, $1''=725.3$ km and an AIA pixel spans $435.2$ km. Vortices of $3$–$10''$ therefore cover $2176$–$7253$ km; the adopted $7000$ km wavelength lies near the upper edge. The quoted thickness $1$–3 pixels corresponds to $435$–$1305$ km. Vortex development from 03:00:13 to 03:13:53 UT lasts 820 s, or 13.7 min.",
"Their nonlinear saturation":r"A 600 s saturation time corresponds to $1.62$–$3.77$ e-folding times for the quoted rates, reproducing the paper’s description of “several” growth times. This is not an independent test because the initial perturbation amplitude is unknown. The measured quantity is the 820 s development interval.",
"A second factor":r"The simulation uses $V_0=5V_{A,xy}$, which reduces the field-free growth rate by $\sqrt{1-(2/5)^2}=0.91652$. Combining this with the unequal-density factor gives $0.84702$. The simulated setup therefore predicts a growth rate about 15 per cent below the quoted equal-density, field-free value.",
"And their own numerics":r"The simulations independently show the same density effect. Increasing the density ratio from unity to 2–3 lowers the growth rate by about 15 per cent. This agrees with the two-density prefactor in the dispersion relation.",
"In an active-region":r"For a 10 G coronal field, the observed hydrodynamic growth rate requires the perturbation wavevector to lie within $0.39^\circ$ of perpendicular to the field. A one-sided-field model gives $0.55^\circ$. The images support a mainly radial field qualitatively, but they do not measure this angle directly.",
"Suppose it did":r"If gravity acted across the interface, stability would require dense plasma below the evacuated region. The opposite orientation is Rayleigh–Taylor unstable and has no long-wavelength Kelvin–Helmholtz cutoff. Under the stable ordering, substituting the solar surface gravity into equation (6.2) gives the counterfactual cutoff below.",
"Inviscid.":r"Equation (3.1) is inviscid. Without another regulator, its Rayleigh–Taylor growth rate has no small-scale bound. Section 4.1 estimates the scale where viscosity matters but does not solve the viscous eigenvalue problem.",
"The interface is sharp":r"The derivation assumes a discontinuous interface. For the coronal event, the estimated value $ka=0.72$ violates this approximation. A finite layer reduces growth and can close the unstable band at short wavelength. Its measured thickness is too uncertain for a quantitative correction here.",
"Linear stability only":r"Except for the mixing-layer scaling in §8, the analysis is linear. It predicts initial growth rates but not nonlinear morphology. Young remnants can already be 3–12 e-folding times old at observable wavelengths, so linear theory may have expired before the structure is imaged. The nonlinear coefficient in Proposition 7 remains uncertain by about a factor of two.",
"No magnetic field":r"Magnetic tension is derived in equation (3.1) but usually set to zero. Section 9.5 instead uses the observed instability to constrain field orientation. The hydrodynamic interpretation requires the wavevector to be within roughly one degree of perpendicular to the unmeasured coronal field. Module 12 develops the magnetic dynamics explicitly.",
}
for p,h in R.items():rep(p,h)
P.write_text(str(s),encoding="utf8");print("rewrote",len(R),"blocks")
