from pathlib import Path
from bs4 import BeautifulSoup
P=Path(__file__).parent/"textbook-edition-20-rule"/"module08.html"
def sh(t,h):
 f=BeautifulSoup(h,"html.parser");t.clear()
 for c in list(f.contents):t.append(c)
s=BeautifulSoup(P.read_text(encoding="utf8"),"html.parser")
def rep(p,h):
 m=[x for x in s.find_all(["p","li","figcaption"]) if x.get_text(" ",strip=True).startswith(p)]
 if len(m)!=1:raise RuntimeError((p,len(m)))
 sh(m[0],h)
R={
"Three hypotheses there":r"The jump conditions assume a steady discontinuity, one polytropic gas, and one temperature on each side. Shock acceleration is negligible for the cases studied here. Trinity violates the constant-$\gamma$ approximation through dissociation, vibration, and radiation. Voyager’s termination shock violates the single-temperature assumption because pickup ions receive most of the dissipated energy.",
"Three remarks on":r"The derivation requires conservation laws in divergence form so they can be integrated across the layer. It also requires uniform endpoint states and excludes finite surface losses of energy. The internal stress, heat flux, thickness, and equation of state need not be specified. Consequently, the jump conditions determine the endpoint states but contain no information about the transition structure.",
"It is worth pausing":r"The jump conditions do not require a viscous model, conductive model, or local thermodynamic equilibrium inside the layer. That independence makes them powerful. Their limitation is equally clear: they determine only the states outside the shock. At the collisionless termination shock, the microscopic layer is far thinner than a collisional mean free path, so a one-temperature closure fails even though conservation still applies.",
"Nothing in Proposition":r"The conservation laws also permit algebraic rarefaction jumps. For $M_1=0.7$ and $\gamma=5/3$, equation (3.1) gives $\rho_2/\rho_1=0.5616$ and $p_2/p_1=0.3625$. Such jumps conserve mass, momentum, and energy but violate the entropy condition. Thermodynamics therefore selects the compressive branch.",
"What happens instead":r"An expansion forms a rarefaction fan rather than a discontinuity. Its characteristics move at different speeds, so the fan broadens continuously with time. Proposition 3 excludes the discontinuous alternative through the entropy condition; a full characteristic derivation lies outside this module.",
"First, internal":r"The numerical Sedov solution satisfies equations that were not used to construct the reduced ODE. Substituting numerical derivatives into the discarded continuity and entropy equations gives residuals below $7\times10^{-9}$ for $0.1\le\lambda\le0.9$. This checks the algebra independently of integrator convergence.",
"Second, external":r"Published similarity constants provide an external check. For $\gamma=5/3$, Tang and Chevalier quote $2.026$ in $R=(2.026Et^2/\rho)^{1/5}$, equivalent to $\xi_0=1.151670$. The present result is $1.151666$. For $\gamma=1.4$, the Kamm–Timmes standard problem implies $\xi_0=1.032777$, matching all six reported figures.",
"The interior of":r"The Sedov solution places most swept-up mass near the shock. For $\gamma=5/3$, half the mass lies outside $0.9392R$, and the density at $0.5R$ is only 1.53 per cent of its post-shock value. Pressure approaches a nearly uniform interior plateau at 30.6 per cent of the post-shock pressure. The remnant is therefore a hot, dilute interior driving a thin dense shell.",
"One honest confound":r"The Trinity residuals change near boundaries between photographic sources, so an instrumental offset could contribute to the block differences. Taylor gives no radius uncertainties with which to test that possibility. Evidence within individual film blocks nevertheless supports real evolution: the earliest point is an outlier within authority A, and the final authority-C points decline monotonically. The interpretation also agrees with the independently computed decline in Mach number.",
"After about 5 ms":r"The strong-shock approximation deteriorates as the blast slows. The inferred Mach number falls from 42.8 at 1.08 ms to 17.3 at 4.61 ms and 3.5 at 62 ms. The compression ratio then falls from nearly the $\gamma=1.4$ ceiling of 6 to about 72 per cent of that value. Increasing ambient-pressure work therefore predicts the observed downward residual trend.",
"Before about 1 ms":r"The earliest flow is also not a freely expanding sphere. The fireball reaches the ground in less than 1 ms, changing the lower boundary. Taylor reports that the upper hemisphere continues to expand nearly spherically, but the geometry is no longer exact.",
"All of this is":r"Figure 3 plots the same 25 Trinity measurements in two ways. The log–log panel shows their overall agreement with similarity scaling. The residual panel exposes systematic offsets and temporal drift that are invisible at the larger scale. The first plot tests the exponent broadly; the second tests whether a single similarity constant fits every epoch.",
"Every shock in":r"Voyager 2 crossed the solar-wind termination shock repeatedly between 30 August and 1 September 2007 at about 84 au. Its plasma instrument recorded the upstream deceleration and downstream state directly, providing an in situ test rather than a remote inference.",
"From the figure caption":r"At Neptune’s bow shock, the measured speed and density change by factors of four in opposite directions, while temperature rises by about a factor of 100. These values provide independent consistency checks on the strong-shock limits.",
"At the termination":r"At the termination shock, density rises only by about two and the thermal-ion temperature by about ten. A single-fluid conversion of the lost bulk energy would instead predict roughly $10^6$ K, compared with the measured $10^5$ K.",
"The authors' explanation":r"Approximately 80 per cent of the proton bulk energy is transferred to pickup ions rather than to the measured thermal population. A single-temperature fluid has no variable for this separate ion component. The solar wind is collisionless at 84 au, so collisions cannot rapidly equilibrate the two populations. The observation therefore rejects the one-temperature closure while preserving the conservation laws.",
"Every comparison of":r"The figure displays measured-to-predicted ratios on a common logarithmic axis. The three Neptune quantities lie near unity. The termination-shock temperature lies near 0.10, showing the one-temperature failure directly. A compression-ratio point is shown only for context because its Mach number comes from the same Rankine–Hugoniot fit.",
"The same paper's":r"For the second crossing, the fitted compression ratio is $2.38\pm0.14$ and the fitted upstream fast-mode Mach number is $4.9\pm0.1$. Gas dynamics would predict 3.556. Although the nominal discrepancy is $8.4\sigma$, it is not an independent test because both quantities come from the same shock fit.",
"First, it is partly":r"The shock orientation is chosen to minimise Rankine–Hugoniot residuals, after which the speed, field angle, and Mach numbers are derived. Compression and Mach number are therefore correlated outputs of one fit. Substituting one into the same jump relation tests internal fit consistency rather than the physical law independently.",
"Take the standard":r"Adopt explosion energy $10^{51}$ erg and ambient hydrogen density $1\ \mathrm{cm^{-3}}$. Including helium gives $\rho_0=2.325\times10^{-24}\ \mathrm{g\,cm^{-3}}$. For the ionised post-shock gas, take $\mu=0.61$ and $\gamma=5/3$.",
"A point explosion in a uniform, pressureless":r"The Sedov solution assumes an instantaneous point explosion in a uniform medium with negligible ambient pressure. Finite source size and radiative energy appear in the earliest Trinity data, while ambient pressure matters after several milliseconds. Circumstellar winds also violate uniform density and require a profile $\rho\propto r^{-s}$.",
"A stated cooling":r"The cooling model in equation (7.2) is a two-power-law approximation rather than a calculated ionisation-equilibrium curve. It predicts a transition radius 57 per cent too large and a transition time 3.1 times too late. These errors quantify the cost of the adopted cooling function.",
}
for p,h in R.items():rep(p,h)
P.write_text(str(s),encoding="utf8");print("rewrote",len(R),"blocks")
