from pathlib import Path
from bs4 import BeautifulSoup
P=Path(__file__).parent/"textbook-edition-20-rule"/"module06.html"
def sh(t,h):
 f=BeautifulSoup(h,"html.parser");t.clear()
 for c in list(f.contents):t.append(c)
s=BeautifulSoup(P.read_text(encoding="utf8"),"html.parser")
def rep(p,h):
 m=[x for x in s.find_all(["p","li","figcaption"]) if x.get_text(" ",strip=True).startswith(p)]
 if len(m)!=1:raise RuntimeError((p,len(m)))
 sh(m[0],h)
R={
"The interstellar gas":r"The neutral interstellar medium is heated mainly by photoelectrons from small grains and PAHs. We approximate this heating as a constant rate $\Gamma$ per hydrogen nucleus. Cooling occurs at rate $n^2\Lambda(T)$ per unit volume. The Koyama–Inutsuka fit combines Lyman-$\alpha$ cooling above about $8000$ K with the [C II] $158\,\mu$m line that cools the cold neutral phase.",
"The slope crosses":r"The logarithmic cooling slope equals unity at two temperatures. The cold turning point is $184.0$ K, with $n=8.682\ \mathrm{cm^{-3}}$ and $P/k=1597.5\ \mathrm{K\,cm^{-3}}$. The warm turning point is $5039.4$ K, with $n=0.994\ \mathrm{cm^{-3}}$ and $P/k=5007.0\ \mathrm{K\,cm^{-3}}$. These states bound the isobarically unstable branch.",
"(9.1) is":r"""Equation (9.1) multiplies thermal balance by $T$ and then differentiates logarithmically. Write $s=d\ln\Lambda/d\ln T$. Along equilibrium, $d\ln n/d\ln T=-s$ and
$$\frac{d\ln P}{d\ln n}=1-\frac{1}{s}.$$
For $s\gt1$, the slope is positive and the branch is stable. For $0\lt s\lt1$, it is negative and the branch is unstable. A pressure between the local minimum and maximum therefore intersects the equilibrium curve three times: twice on stable outer branches and once on the unstable middle branch. ∎""",
"Wolfire, McKee":r"Wolfire et al. (2003) computed a more detailed equilibrium curve using measured gas-phase abundances, grain and PAH photoelectric heating, and [C II] and [O I] cooling. The comparison uses their solar-neighbourhood row at $R=8.5$ kpc and cloud column $10^{19}\ \mathrm{cm^{-2}}$.",
"The window is narrow":r"The predicted coexistence interval spans a factor $3.13$ in pressure but factors $8.7$ in density and $27.4$ in temperature. Pressure is therefore the sharper observational diagnostic. Jenkins and Tripp measured a mean pressure of $2240\ \mathrm{K\,cm^{-3}}$ in 2001 and produced a larger revised survey in 2011. Section 10 compares the latter distribution with the theoretical interval.",
"The content of that":r"Wolfire et al. predict the location and width of the pressure window from independently constrained heating and cooling physics. Gas-phase carbon and oxygen abundances come from absorption measurements, while PAH abundance comes from infrared emission. Their parameter $\varphi_{\rm PAH}=0.5$ was calibrated using a C I/C II column-density ratio. The later Jenkins–Tripp pressure distribution was not used to fit either edge of the window.",
"$\\varphi_{\\rm PAH}$ is":r"The PAH parameter materially shifts the prediction. Across $\varphi_{\rm PAH}=0.25$–1, Wolfire et al. find a factor $1.5$ change in $P_{\min}$ and a factor $1.9$ change in $P_{\max}$. At $0.25$, the upper boundary falls by about 35 per cent. The comparison must therefore retain the independent constraints on this parameter.",
"What mitigates":r"Wolfire et al. test four non-standard variants against observables other than pressure. Low $\varphi_{\rm PAH}$ and low PAH abundance underpredict C I excitation and C$^+$ cooling. High $\varphi_{\rm PAH}$ overpredicts temperature and C I/C II, while low radiation field overpredicts C I/C II. They regard the high-$\varphi_{\rm PAH}$ and low-radiation variants as securely excluded.",
"Fig. 4 puts":r"Figure 4 compares the predicted pressure windows with the measured distribution. Its lower panel isolates the disagreement by showing the fraction of cold gas below the theoretical minimum pressure.",
"The same failure":r"Warm neutral gas provides an independent challenge to a static two-phase picture. Heiles and Troland (2003) find that at least 48 per cent of the warm H I column lies between 500 and 5000 K, inside the nominal unstable range. They also find that warm gas supplies at least 61 per cent of the high-latitude H I column. Both values are column-weighted lower bounds.",
"The anchor. Upper":r"Upper panel: Wolfire et al. predict coexistence between $1960$ and $4810\ \mathrm{K\,cm^{-3}}$, with mean pressure $3070$. The analytic fit gives $1597$–$5007$. Jenkins and Tripp measure a median $3801.9\ \mathrm{K\,cm^{-3}}$ with dispersion $0.175$ dex, inside both windows. Lower panel: a static model permits no cold gas below $P_{\min}$, while the fitted lognormal gives 5 per cent. The observed fractions are 29 per cent for the full sample and 23 per cent under weak starlight.",
"Linear stability only":r"The Schwarzschild and Field criteria determine whether infinitesimal perturbations grow, but they do not predict the nonlinear state. The observed pressure distribution reflects turbulent evolution, phase exchange, and finite-amplitude structure. Linear theory can therefore show that the static equilibrium prediction fails without specifying the resulting distribution.",
"The solar opacity":r"Section 3.2 reads the rise of $\nabla$ from a solar-model table. It does not compute the opacity or separate its contribution from the temperature dependence. The inferred convective boundary is therefore conditional on the tabulated model physics.",
"Thermal instability.":r"Field, G. B. (1965), “Thermal Instability”, <i>ApJ</i> <b>142</b>, 531. Equations (1)–(4b) define the net loss function and give the isochoric and isobaric criteria. Condensation modes obey the isobaric criterion. The commonly used derivative of $\mathcal L/T$ is equivalent only on the equilibrium curve.",
"The two-phase window":r"Wolfire, M. G. et al. (2003), “Neutral Atomic Phases of the Interstellar Medium in the Galaxy”, <i>ApJ</i> <b>587</b>, 278–311, arXiv:astro-ph/0207098. Tables 3 and 4 provide the standard pressure window and its parameter variations. Section 8.1 documents the observational constraints on PAH heating and compares the earlier Jenkins–Tripp mean pressure.",
"The measured pressures":r"Jenkins, E. B. &amp; Tripp, T. M. (2011), <i>ApJ</i> <b>734</b>, 65, arXiv:1104.2323. Their C I survey gives a mass-weighted lognormal with mean $\log(p/k)=3.58$ and dispersion at least $0.175$ dex. They find 29 per cent of the full sample and 23 per cent of the low-starlight sample below the static-CNM minimum pressure.",
"Paper I, cited":r"Jenkins, E. B. &amp; Tripp, T. M. (2001), <i>ApJS</i> <b>137</b>, 297–340, arXiv:astro-ph/0107177. Its mean pressure $2240\ \mathrm{K\,cm^{-3}}$ enters through Wolfire et al.’s comparison. This earlier survey is distinct from the 2011 pressure distribution used as the principal measurement here.",
"The warm-side":r"Heiles, C. &amp; Troland, T. H. (2003), <i>ApJ</i> <b>586</b>, 1067–1093, arXiv:astro-ph/0207105. At least 48 per cent of the warm H I column lies between 500 and 5000 K, and at least 61 per cent of high-latitude H I is warm. The cold-phase spin-temperature distribution peaks near 40 K and has column-weighted median 70 K.",
"The textbook results":r"Kippenhahn, R. &amp; Weigert, A., <i>Stellar Structure and Evolution</i> (1990), §§6.1, 7.2, and 14.3. These sections provide the Schwarzschild and Ledoux criteria, the efficient-limit mixing-length relations, and the partially ionised adiabatic gradient.",
"Constants and standards":r"Physical constants use CODATA 2018. Solar nominal quantities use IAU 2015 Resolution B3. Atmospheric lapse rate and reference temperatures use ISO 2533:1975 and the US Standard Atmosphere 1976.",
}
for p,h in R.items():rep(p,h)
P.write_text(str(s),encoding="utf8");print("rewrote",len(R),"blocks")
