from pathlib import Path
from bs4 import BeautifulSoup
P=Path(__file__).parent/"textbook-edition-20-rule"/"module06.html"
def sh(t,h):
 f=BeautifulSoup(h,"html.parser");t.clear()
 for c in list(f.contents):t.append(c)
s=BeautifulSoup(P.read_text(encoding="utf8"),"html.parser")
def rep(p,h):
 m=[x for x in s.find_all(["p","li","figcaption"]) if x.get_text(" ",strip=True).startswith(p)]
 if len(m)!=1:raise RuntimeError((p,len(m)))
 sh(m[0],h)
R={
"Setup for Proposition":r"A parcel begins where the ambient pressure is $P_0$ and moves upward by $\delta r$ to pressure $P_1$. Sound waves keep it in pressure balance with its surroundings, while the parcel itself changes adiabatically. At $P_1$, buoyancy depends on whether its temperature $T_{\rm p}$ exceeds the ambient temperature. At equal pressure and composition, the hotter ideal gas is less dense.",
"Archimedes' principle":r"A parcel whose density differs from its surroundings by $\Delta\rho$ experiences buoyant acceleration $-g\Delta\rho/\rho$. Equation (2.3) gives $g(\nabla-\nabla_{\rm ad})\delta r/H$. The acceleration reinforces the displacement when $\nabla\gt\nabla_{\rm ad}$ and opposes it when $\nabla\lt\nabla_{\rm ad}$. These are the unstable and stable cases, respectively. ∎",
"Four premises were":r"The derivation assumes uniform composition, rapid pressure equilibration, and adiabatic parcel motion. Section 4 relaxes the composition assumption. At the photosphere, §6 gives $v_c/c_s=0.4271$, so pressure equilibration is only moderately faster than the parcel motion. Radiation there carries $98.7$ per cent of the flux, making adiabatic motion even less secure. The criterion remains most reliable deeper in the convection zone.",
"Equation (3.1) is":r"Equation (3.1) attaches a timescale to the Schwarzschild criterion. Near marginal stability, $N^2$ is the small difference between $\nabla$ and $\nabla_{\rm ad}$, each of order $0.4$. A tabulated stellar model must therefore resolve both gradients accurately before their difference can be trusted.",
"Read the $\\nabla$":r"In the solar model, $\nabla$ reaches a minimum of $0.1937$ near $0.4531R$ and then rises outward. It crosses the nearly constant adiabatic value $0.3957$ at $0.7269R$, where $T=2.02\times10^6$ K. Sparse tabulation slightly obscures the minimum but not the crossing. This radius defines the base of the model convection zone.",
"It is worth being exact":r"The convection zone begins because the radiative gradient rises to the flat adiabatic plateau. The plateau itself does not move appreciably in this region. Since $\nabla_{\rm rad}\propto\kappa LP/(mT^4)$, increasing opacity and decreasing temperature can both raise the radiative gradient. The model table establishes the rise but does not separate these contributions; that would require its opacity data.",
"For an ideal gas $\\rho":r"For an ideal gas, $\rho=\mu m_uP/(k_BT)$. The parcel retains its composition, whereas the surroundings may have $\Delta\ln\mu\ne0$. Pressure balance cancels the pressure terms when their densities are compared. The temperature difference contributes $-(\nabla_{\rm ad}-\nabla)\Delta\ln P$, and the composition gradient contributes $-\nabla_\mu\Delta\ln P$.",
"For a general equation":r"A general equation of state introduces $\delta=-(\partial\ln\rho/\partial\ln T)_{P,\mu}$ and $\varphi=(\partial\ln\rho/\partial\ln\mu)_{P,T}$. Equation (4.1) then gains an overall factor $\delta$ and a coefficient $\varphi/\delta$ on $\nabla_\mu$. Both coefficients equal unity for the ideal gases used here.",
"The sign is the":r"If molecular weight increases inward, then $\nabla_\mu\gt0$. A parcel displaced upward retains its larger molecular weight and is denser than its new surroundings. The composition gradient is therefore stabilising and can suppress convection even when $\nabla\gt\nabla_{\rm ad}$.",
"Equation (2.5) assumed":r"Equation (2.5) assumes constant $\gamma$. During partial ionisation, compression supplies ionisation energy as well as thermal energy. The parcel therefore warms less than a fully neutral or fully ionised gas under the same compression. This additional energy reservoir can reduce $\nabla_{\rm ad}$ substantially.",
"The size of the effect":r"The parameter $\Phi$ measures the ionisation energy relative to thermal energy. Near the deepest depression, $\chi_{\rm H}/(k_BT)$ is about 12, so ionisation dominates the heat capacity. The resulting change in $\nabla_{\rm ad}$ is therefore large rather than perturbative. Table 2 evaluates the Saha fraction and adiabatic gradient along the photospheric isobar.",
"The minimum does not":r"The minimum in $\nabla_{\rm ad}$ does not occur at half ionisation. At fixed $\Phi$, the dependence enters through $x(1-x)$, which peaks at $x=1/2$. Along an isobar, however, $\Phi$ decreases as temperature rises. Their combined variation moves the minimum to $x=0.3271$. Problem K1 shows that increasing pressure shifts the minimum to higher temperature.",
"The range of turnover":r"The local turnover time changes strongly with depth. It is $21.66$ d at $0.750R$, $8.38$ h at $0.9831R$, and $1.38$ min at the photosphere. This factor of roughly $2\times10^4$ is compatible with a mixing length proportional to the local pressure scale height.",
"Abramenko et al.":r"Abramenko et al. (2012) measured solar granules with the New Solar Telescope. A Gaussian fit to their regular-granule population gives mean diameter $1050\pm22$ km and width $480\pm11$ km.",
"Oba, Iida":r"Oba, Iida, and Shimizu (2017) measured photospheric velocities from Hinode Fe I $630.15$ nm spectra after filtering the five-minute oscillation. Their mean upflow falls from $0.65\ \mathrm{km\,s^{-1}}$ at 40 km to $0.40\ \mathrm{km\,s^{-1}}$ at 163 km. The rms convective velocity decreases from about $0.6$ to $0.3\ \mathrm{km\,s^{-1}}$ across the same sampled range.",
"This subsection uses":r"The flux estimate combines four approximations. The density at optical depth $2/3$ comes from the adopted solar model. A single-depth Planck function converts intensity contrast to temperature contrast. Multiplying a mean upflow speed by an rms temperature contrast assumes perfect correlation. Finally, the velocity is measured at optical depth $0.55$, whereas $\rho$ and $c_P$ are evaluated at $2/3$.",
"At $\\lambda = 705.7":r"At $705.7$ nm and $5772$ K, the Planck sensitivity is $d\ln B_\lambda/d\ln T=3.6386$. The observed intensity contrast $0.155$ therefore implies $\delta T/T=0.04260$, or $\delta T=245.9$ K. Treating intensity contrast as temperature contrast would overestimate the inferred convective flux by a factor of $3.64$.",
"Let the gas sit":r"Let the equilibrium satisfy $\mathcal L(\rho_0,T_0)=0$ and perturb its temperature by $\delta T$. The energy equation gives $c\,\dot{\delta T}=-\delta\mathcal L$, with positive heat capacity $c$. The perturbation grows when $\delta\mathcal L$ opposes $\delta T$. At fixed density, this requires $(\partial\mathcal L/\partial T)_\rho\lt0$, which is Field’s isochoric criterion.",
}
for p,h in R.items():rep(p,h)
P.write_text(str(s),encoding="utf8");print("rewrote",len(R),"blocks")
