from pathlib import Path
from bs4 import BeautifulSoup
P=Path(__file__).parent/"textbook-edition-20-rule"/"module09.html"
def sh(t,h):
 f=BeautifulSoup(h,"html.parser");t.clear()
 for c in list(f.contents):t.append(c)
s=BeautifulSoup(P.read_text(encoding="utf8"),"html.parser")
def rep(p,h):
 m=[x for x in s.find_all(["p","li","figcaption"]) if x.get_text(" ",strip=True).startswith(p)]
 if len(m)!=1:raise RuntimeError((p,len(m)))
 sh(m[0],h)
R={
"Contrast this":r"In a plane-parallel atmosphere with constant gravity, $\int g\,dz$ diverges and pressure can decay exponentially to zero. For inverse-square gravity, the integral to infinity is finite. An isothermal spherical atmosphere therefore approaches a nonzero pressure at infinity. Without an external medium supplying that pressure, the static solution cannot exist.",
"Parker made":r"Parker’s 1958 conductive-corona model reaches the same conclusion with a declining temperature. From $N_0=3\times10^7\ \mathrm{cm^{-3}}$ and $T_0=1.5\times10^6$ K, he obtains $p_0\approx1.3\times10^{-2}\ \mathrm{dyn\,cm^{-2}}$. His asymptotic pressure is about $6\times10^{-6}\ \mathrm{dyn\,cm^{-2}}$, more than seven orders of magnitude above his adopted interstellar pressure.",
"His conclusion":r"Parker concludes that no plausible external pressure can balance the calculated coronal pressure at infinity. The corona must therefore expand rather than remain hydrostatic. The present derivation reconstructs this argument with modern inputs.",
"Note what $r_c$":r"The critical radius is determined by the gas temperature rather than fitted. It satisfies $c_T^2=GM/(2r_c)$, or equivalently $v_{\rm esc}(r_c)=2c_T$. Problem C1 checks this identity numerically.",
"Fig. 2 draws":r"Figure 2 shows equation (3.3) as level curves in the $(x,u)$ plane. The six solution families are different contours of one implicit relation. Only the transonic wind and accretion contours pass smoothly through the saddle point $(1,1)$.",
"The numbers confirm":r"The asymptotic speed $u\simeq2\sqrt{\ln x}$ converges slowly. At $x=30$, $10^3$, and $10^6$, the exact values are $3.651$, $5.288$, and $7.503$. The approximations are $3.688$, $5.257$, and $7.434$. Because the logarithmic slope decreases only as $1/\ln x$, changing temperature cannot reproduce an arbitrarily small observed acceleration.",
"The isothermal assumption":r"The data reject an isothermal wind, so we next allow a polytropic equation of state. This extension yields a critical-point constraint, $\gamma\lt3/2$, before any observational fitting. The constraint can therefore be tested independently.",
"Repeating the derivation":r"For $P=K\rho^\gamma$, the sound speed varies with radius. The critical conditions remain $v=c$ and $2c^2/r=GM/r^2$, but they now determine the critical radius implicitly. The local derivative through this point supplies the additional bound on $\gamma$.",
"Two checks on":r"Equation (5.2) has the correct limiting behaviour. At $\gamma=1$, $r_c=GM/(2c_\infty^2)=R_B/4$. At $\gamma=5/3$, the critical radius tends to zero and the Bondi eigenvalue is obtained as a limit. This is why the Sgr A* calculation uses $\lambda=1/4$ without assigning a finite sonic radius.",
"With the Baumbach":r"The isothermal mass flux is extremely temperature-sensitive. For the adopted base density, raising $T$ from 1 to 2 MK increases $\dot M$ from $2.90\times10^{11}$ to $5.39\times10^{13}\ \mathrm{g\,s^{-1}}$, a factor 186. Agreement within a factor of a few therefore provides little evidence for a unique coronal temperature.",
"Helios 1":r"Helios 1 and 2 measured solar-wind density, speed, temperature, and magnetic field between $0.29$ and $0.98$ au. Venzmer and Bothmer (2018) fit each variable as $x(r)=d\,r^e$ and reported separate mean and median coefficients. Their Table 3 supplies the observational anchor.",
"Each exponent was":r"The four exponents were fitted independently, without imposing a fluid model. Year-to-year scatter across the solar cycle is reported alongside formal fit uncertainty. The larger scatter measures the repeatability of each exponent and is used for the physical comparisons below.",
"A reader who":r"Module 2 uses the same Helios table to test steady spherical continuity and an adiabatic temperature law. Reusing the measurements here does not create independent data. The present tests concern different predictions: critical-point existence, solution-family sign, and the radial momentum balance.",
"This module uses":r"Three tests are new. The fitted temperature and density slopes constrain the polytropic index relative to the bound $\gamma\lt3/2$. The positive speed exponent distinguishes an accelerating wind from a breeze. Finally, the measured pressure gradient predicts the velocity gradient through the momentum equation.",
"Proposition 3 gives":r"A transonic wind accelerates and has $\beta\gt0$, while a breeze approaches $v\propto r^{-2}$ and has $\beta\lt0$. A static corona has no velocity exponent. Helios gives $\beta=0.049\pm0.010$ for mean fits and $0.058\pm0.013$ for median fits, selecting the accelerating-wind family.",
"Increasing $T_0$":r"Even a decade increase in temperature reduces the isothermal logarithmic slope by only 36–52 per cent over the tested range. This weak response follows from the asymptotic $1/(2\ln x)$ dependence. Temperature adjustment cannot bring the model slope down to the Helios value.",
"First, a polytropic":r"A polytropic wind with $\gamma\gt1$ requires sufficient base enthalpy to reach its critical point. Bernoulli’s constant at a nearly static base is $c_0^2/(\gamma-1)-GM/r_0$. At the critical point it is positive for $1\lt\gamma\lt5/3$. A transonic solution therefore requires $c_0^2/(\gamma-1)\gt GM/r_0$, which sets a minimum launch temperature.",
"Third, that same":r"The forced polytropic solution also misses both temperature and acceleration at 1 au. It predicts $5.817\times10^4$ K, only 60.2 per cent of the measured temperature. Its velocity exponent is $0.00802$, smaller than the measured mean value by a factor of 6.1.",
"At 1 au":r"For the mean Helios fits, $v=435.6\ \mathrm{km\,s^{-1}}$, $T=9.670\times10^4$ K, and $n_p=7.57\ \mathrm{cm^{-3}}$. The fitted pressure exponent gives a dimensionless pressure acceleration $+0.02112$, while gravity contributes $-0.00468$. Their sum is the momentum-equation prediction compared below.",
"A careful reader":r"The predictor is not completely independent of the measured velocity slope because steady continuity relates the density and speed exponents. Enforcing $\alpha=2+\beta$ changes the predicted slope from $0.01644$ to $0.01674$, only 1.8 per cent. The measured-to-predicted ratio remains about three.",
"Verscharen, Bale":r"Ulysses measurements give radial mass fluxes per steradian near $3.5\times10^{-16}$ and $2.2\times10^{-16}$ au$^2$ g cm$^{-2}$ s$^{-1}$ in two polar scans. Equatorial values span $1$–$15\times10^{-16}$. Multiplying by $4\pi\,\mathrm{au}^2$ converts these to total rates. Because Helios sampled the ecliptic, the equatorial interval is the appropriate comparison.",
"The inverse is":r"Inverting the calculation exposes the uncertain base density. Matching the observed mass flux requires electron densities from $5.78\times10^6$ to $1.07\times10^9\ \mathrm{cm^{-3}}$ as temperature varies from 2 to 1 MK. This factor 186 exceeds the precision of the extrapolated Baumbach–Allen base density, so the mass-flux agreement is weak evidence.",
"The mass is":r"GRAVITY stellar orbits give $M=4.30\times10^6M_\odot$ for Sgr A*. Chandra measurements near the Bondi radius give $n_e\approx130\ \mathrm{cm^{-3}}$ and $kT_e\approx2$ keV. We take $\gamma=5/3$ and $\mu\approx0.70$ for fully ionised, metal-rich gas.",
"Those inputs give":r"The inputs give $\rho=1.5221\times10^{-22}\ \mathrm{g\,cm^{-3}}$ and $c_\infty=675.4\ \mathrm{km\,s^{-1}}$, close to the quoted $670\ \mathrm{km\,s^{-1}}$. The resulting Bondi radius is $0.0811$ pc. For $\gamma=5/3$, the critical radius tends to zero and the limiting eigenvalue is $\lambda=1/4$.",
"Baganoff et al. computed":r"Baganoff et al. obtain $\dot M_B\approx3\times10^{-6}M_\odot\,\mathrm{yr^{-1}}$ using the then-standard black-hole mass $2.6\times10^6M_\odot$. Rescaling their result by $M^2$ to the GRAVITY mass gives $8.15\times10^{-6}M_\odot\,\mathrm{yr^{-1}}$. This checks normalization rather than testing Bondi physics.",
"A second consistency":r"Their local plasma estimate uses $kT\approx1.3$ keV and $n_e\approx26\ \mathrm{cm^{-3}}$, giving a quoted rate near $10^{-6}M_\odot\,\mathrm{yr^{-1}}$. The present formula at their adopted mass gives $1.13\times10^{-6}$, confirming the arithmetic to 13 per cent.",
"Each premise, on":r"Rotation, outflow, and weak collisionality can each reduce the spherical Bondi rate. They act in the same direction and can accommodate the range of observed deficits. The calculation is useful because it quantifies how strongly a well-defined spherical prediction fails, thereby measuring the importance of omitted physics.",
}
for p,h in R.items():rep(p,h)
P.write_text(str(s),encoding="utf8");print("rewrote",len(R),"blocks")
